### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by Skiez6055** [D3AD-E/DeLLa#4]
Got the file path for Lunar corrected. However, I still cannot get this project to function. Nothing would not even work. Is the source code damaged??

Whenever i do the simple dotnet add package Lunar --version 1.4.10 in CMD. I expected everything to not work. Then of course. it failed. 

"C:\Users\User\Desktop\DeLLa-master>dotnet add package Lunar --version 1.4.10
  Determining projects to restore...
  Writing C:\Users\User\AppData\Local\Temp\tmp78CD.tmp
info : Adding PackageReference for package 'Lunar' into project 'C:\Users\User\Desktop\DeLLa-master\DeLLaGUI.csproj'.
info : Restoring packages for C:\Users\User\Desktop\DeLLa-master\DeLLaGUI.csproj...
info : Package 'Lunar' is compatible with all the specified frameworks in project 'C:\Users\User\Desktop\DeLLa-master\DeLLaGUI.csproj'.

error: Value cannot be null. (Parameter 'path1')"

**Comment by Skiez6055** [comment]
UPDATE: Neverminded on that. its working now BUT

I now have a new problem! Wooo!

Basically both "using Lunar.Assembly; AND using Lunar.Assembly.Structures;" are giving me:

The type or namespace name 'Assembly' does not exist in the namespace 'Lunar' (are you missing an assembly reference?)

**Comment by D3AD-E** [comment]
If you are using Visual Studio, right click on project and add reference to Lunar if you have not already.
Guy working on Lunar has updated it recenly, remove these 2 using statements, and it should be working.
